export {default as MovieCard} from "./movieController/MovieCard"
export { default as MovieList } from "./movieController/MovieList"
export { default as MovieDetails } from "./MovieDetails"
export { default as Navbar } from "./Navbar"
export {default as Home } from "./Home"